### ISSUE TITLE
Agregar GA para mozilla

### ISSUE THREAD

**Issue by deimidis** [mozillahispano/quienestadetrasdefirefox.org#11]
Tenemos que agregar el registro de Mozilla para GA para que puedan ver las estadísticas. El código que pusieron en el bug https://bugzilla.mozilla.org/show_bug.cgi?id=878053 

<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-35433268-36']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>

Desconozco si se puede agregar uno o como se hace

**Comment by nukeador** [comment]
@deimidis ¿Y el GA que tenemos ahora de quién es o quién lo gestiona?

```
<script type="text/javascript">
  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-41627038-1']); // This is my account number, I have added the zeros in this editor
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();
</script>
```

@bernimel ¿Tenemos que mantener dos GA?

**Comment by bernimel** [comment]
El que tenemos es el nuestro, al menos en la cuenta GA de MH aparecen los datos. Este último que envía Guillermo entiendo que lo solicita Mozilla para tener control. Es algo tarde porque ya no tiene apenas tráfico, no van a recibir mucho dato a no ser que se vuelva a comunicar el site.

**Comment by nukeador** [comment]
Quedo a la espera de que me digáis que dejo o que pongo entonces.

**Comment by bernimel** [comment]
¿Solo puede haber uno? ¿Es como los inmortales?

**Comment by nukeador** [comment]
No se si se pega uno con el otro, como me digáis, no soy experto en GA :P

**Comment by nukeador** [comment]
@bernimel @deimidis Lo que me digáis hago.

**Comment by bernimel** [comment]
Yo la verdad que no tengo mucha idea. Aquí dicen alguna cosa, por si sirve: http://analyticsblog.es/dos-codigos-de-seguimiento-de-google-analytics-en-una-misma-web/

**Comment by nukeador** [comment]
Sería bueno ponerlo en el bug para que nos confirmen el código final que incluya ambos y no la liemos.

**Comment by bernimel** [comment]
¿Y si les damos acceso a los datos y chim pum?

**Comment by nukeador** [comment]
Creo que ellos quieren tenerlo centralizado y demás, habladlo y lo que os digan.
