### ISSUE TITLE
Cargar siempre sin www

### ISSUE THREAD

**Issue by nukeador** [mozillahispano/quienestadetrasdefirefox.org#5]
Deber cargar siempre la web sin www

**Comment by willyaranda** [comment]
Estamos usando apache para servir estáticos?

**Comment by nukeador** [comment]
Es lo que me estoy dando cuenta, que lo sirve nginx y por eso no hace el redirect si accedes directamente.

@willyaranda ¿es posible que esté pasando eso?

**Comment by willyaranda** [comment]
Entonces el .htaccess no vale para nada. Sube el fichero de configuración
de nginx que lo está sirviendo directamente.

**Comment by nukeador** [comment]
Uhmmm, entonces habría que replicar el comportamiento de el htaccess en nginx, ¿es posible?

De todas formas veo que el htaccess si está aplicando el cambio de www a no www.

**Comment by willyaranda** [comment]
Mañana miro a ver cómo lo has montado y respondo con propiedad!

**Comment by willyaranda** [comment]
Sí, lo veo bastante sencillo para replicar sin mucho trabajo.

Me pongo con ello.

**Comment by willyaranda** [comment]
Acabo de cambiar a nginx. Me falta el redirect de /mobile a /mobile.html. Cuando lo tenga, subo el fichero de configuración.

**Comment by nukeador** [comment]
Ping @willyaranda hemos publicado la web ya, ¿esto funciona?

**Comment by willyaranda** [comment]
Sí, sorry. Todo el www va a sin www. Está en https://github.com/mozillahispano/quienestadetrasdefirefox.org/blob/master/nginx.conf#L6
